BOT_CHANNEL_WHITELIST = []
BOT_CHANNEL_BLACKLIST = []
BOT_CHANNEL_REGEX = r'^bots?($|[-_].*)'

BOT_ROLE_WHITELIST = []
BOT_ROLE_BLACKLIST = []
BOT_SUPERUSER_ROLES = ['admin', 'administrator', 'mod', 'moderator']

OPT_ROLE_PREFIX = 'In:'

AUTO_ROLE_PREFIX = '(Auto)'

COLORS_ROLE_PREFIX = ''
COLORS_LIMIT_PALETTE = False
COLORS_MIN_LUMINANCE = 0.15
COLORS_MAX_LUMINANCE = 0.70

AGE_ADULT_ROLE = 'Adult'
AGE_MINOR_ROLE = 'Minor'
